#???
server:
  port: 8082
#?????
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #   ?????
    url: jdbc:mysql://localhost:3306/mall?zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??
  global-config:
    db-config:
      id-type: auto

